Repository Ubugeeei/chibivue, pull requests merged in 2023-12, with the labels that each got.

#187 feat:💪 render mermaid in md #183
  book/online-book/.vitepress/config/index.ts
  package.json
  pnpm-lock.yaml
Labels: bug

#191 other: #189 🔹 notify deployment
  .github/workflows/deploy.yml
Labels: dx

#197 other: #196 🔹 remove reactive effect deps
  book/impls/10_minimum_example/030_reactive_system/packages/reactivity/effect.ts
  book/impls/10_minimum_example/040_vdom_system/packages/reactivity/effect.ts
  book/impls/10_minimum_example/050_component_system/packages/reactivity/effect.ts
  book/impls/10_minimum_example/050_component_system2/packages/reactivity/effect.ts
  book/impls/10_minimum_example/050_component_system3/packages/reactivity/effect.ts
  book/impls/10_minimum_example/060_template_compiler/packages/reactivity/effect.ts
  book/impls/10_minimum_example/060_template_compiler2/packages/reactivity/effect.ts
  book/impls/10_minimum_example/060_template_compiler3/packages/reactivity/effect.ts
  book/impls/10_minimum_example/070_sfc_compiler/packages/reactivity/effect.ts
  book/impls/10_minimum_example/070_sfc_compiler2/packages/reactivity/effect.ts
  book/impls/10_minimum_example/070_sfc_compiler3/packages/reactivity/effect.ts
  book/impls/10_minimum_example/070_sfc_compiler4/packages/reactivity/effect.ts
  book/impls/20_basic_virtual_dom/010_patch_keyed_children/packages/reactivity/effect.ts
  book/impls/20_basic_virtual_dom/020_bit_flags/packages/reactivity/effect.ts
  book/impls/20_basic_virtual_dom/040_scheduler/packages/reactivity/effect.ts
  book/impls/20_basic_virtual_dom/050_next_tick/packages/reactivity/effect.ts
  book/impls/20_basic_virtual_dom/060_other_props/packages/reactivity/effect.ts
  book/impls/30_basic_reactivity_system/010_ref/packages/reactivity/effect.ts
  book/impls/30_basic_reactivity_system/020_shallow_ref/packages/reactivity/effect.ts
  book/impls/30_basic_reactivity_system/030_to_ref/packages/reactivity/effect.ts
  book/impls/30_basic_reactivity_system/040_to_refs/packages/reactivity/effect.ts
  book/impls/30_basic_reactivity_system/050_computed/packages/reactivity/effect.ts
  book/impls/30_basic_reactivity_system/060_computed_setter/packages/reactivity/effect.ts
  book/impls/30_basic_reactivity_system/070_watch/packages/reactivity/effect.ts
  book/impls/30_basic_reactivity_system/080_watch_api_extends/packages/reactivity/effect.ts
  book/impls/30_basic_reactivity_system/090_watch_effect/packages/reactivity/effect.ts
  book/impls/30_basic_reactivity_system/100_reactive_proxy_target_type/packages/reactivity/effect.ts
  book/impls/30_basic_reactivity_system/110_template_refs/packages/reactivity/effect.ts
  book/impls/30_basic_reactivity_system/120_proxy_handler_improvement/packages/reactivity/effect.ts
  book/impls/30_basic_reactivity_system/130_cleanup_effects/packages/reactivity/effect.ts
  book/impls/30_basic_reactivity_system/140_effect_scope/packages/reactivity/effect.ts
  book/impls/30_basic_reactivity_system/150_other_apis/packages/reactivity/effect.ts
  book/impls/40_basic_component_system/010_lifecycle_hooks/packages/reactivity/effect.ts
  book/impls/40_basic_component_system/020_provide_inject/packages/reactivity/effect.ts
  book/impls/40_basic_component_system/030_component_proxy/packages/reactivity/effect.ts
  book/impls/40_basic_component_system/040_setup_context/packages/reactivity/effect.ts
  book/impls/40_basic_component_system/050_component_slot/packages/reactivity/effect.ts
  book/impls/40_basic_component_system/060_slot_extend/packages/reactivity/effect.ts
  book/impls/40_basic_component_system/070_options_api/packages/reactivity/effect.ts
  book/impls/50_basic_template_compiler/010_transformer/packages/reactivity/effect.ts
  book/impls/50_basic_template_compiler/020_v_bind/packages/reactivity/effect.ts
  book/impls/50_basic_template_compiler/022_transform_expression/packages/reactivity/effect.ts
  book/impls/50_basic_template_compiler/025_v_on/packages/reactivity/effect.ts
  book/impls/50_basic_template_compiler/027_event_modifier/packages/reactivity/effect.ts
  book/impls/50_basic_template_compiler/027_event_modifier2/packages/reactivity/effect.ts
  book/impls/50_basic_template_compiler/030_fragment/packages/reactivity/effect.ts
  book/impls/50_basic_template_compiler/035_comment/packages/reactivity/effect.ts
  book/impls/50_basic_template_compiler/040_v_if_and_structural_directive/packages/reactivity/effect.ts
  book/impls/50_basic_template_compiler/050_v_for/packages/reactivity/effect.ts
  book/impls/50_basic_template_compiler/060_resolve_components/packages/reactivity/effect.ts
  book/online-book/src/10-minimum-example/030-minimum-reactive.md
  book/online-book/src/20-basic-virtual-dom/030-scheduler.md
  book/online-book/src/30-basic-reactivity-system/040-effect-scope.md
  book/online-book/src/en/10-minimum-example/030-minimum-reactive.md
  book/online-book/src/en/20-basic-virtual-dom/030-scheduler.md
  book/online-book/src/en/30-basic-reactivity-system/040-effect-scope.md
  packages/reactivity/src/effect.ts
Labels: implement, online book, fix
